#!/bin/bash
set -e

if [ -e /usr/sbin/update-grub ]; then
  if [ -e /boot/grub/grub.cfg ]; then
  	update-grub
  fi
fi


if [ -e /usr/sbin/update-initramfs ]; then
  if [ -e /boot/initrd ]; then
  	update-grub
  fi
fi
